package com.example.mysomm;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

public class HomePage extends AppCompatActivity {

    private Button wineDishButton;
    private Button wineCollectionButton;
    private Button wineSurveyButton;
    private Button singOut;
    private Button help;

    DbHelper dbHelper = new DbHelper(this);

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        wineDishButton = findViewById(R.id.wineDishButton);
        wineCollectionButton = findViewById(R.id.wineCollectionButton);
        wineSurveyButton = findViewById(R.id.wineSurveyButton);
        singOut = findViewById(R.id.btnSingOut);
        help = findViewById(R.id.btnHelp);

        fillDatabase();

        wineDishButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                openWineDishes();
            }
        });

        wineCollectionButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                openWineCollection();
            }
        });




        wineSurveyButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                openWineSurvery();
            }
        });

        singOut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                openProfileSetUp();
            }
        });

        help.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                openOnboardingAHelp();
            }
        });



        }



    public void fillDatabase()
    {
        dbHelper.deleteAllRows();
        dbHelper.saveToLocalDatabase("Pacific Rim Sweet Riesling","Riesling","Between","Moderately sweet with flavors of pineapple, peach, and hints of honey. The finish is bright and crisp which cleanses the palate and provides good balance to the upfront fruit.", "Light", "White", "Columbia Valley, Washington", "Very", "Less than $20", "https://images.vivino.com/thumbs/uX9zZ6CqS8KIWIGtqK7gGA_pb_x960.png");
        dbHelper.saveToLocalDatabase("Savannah Rosé","Rosé","Between","This sweet Rose has bold flavors of strawberry, peaches, and rose petal. Fruit-forward and sweet, this would be the perfect summer and spring drink to sip on all day long!", "Light", "Red", "Texas", "Not Very", "Less than $20", "https://filemanager-dfw.orderport.net/FiestaVineyardWinery/Catalog/40f862a1-c4b0-42b6-9bfb-d19c1b1a9f0d-Large.png?ts=637097745979370000");
        dbHelper.saveToLocalDatabase("Hunt and Harvest Merlot","Merlot","Dry","The wine has lifted aromatics of red plum, dark cherry, and dusty milk chocolate. The fruit on the palate is bright with satsuma plum and red berries. The finish has touches of bitter dark chocolate.", "Light", "White", "Napa Valley, California", "Not Very", "Greater than $20", "https://images.vivino.com/thumbs/uvX4ikh7QWqoRNHFbLJERA_pb_x600.png");
        dbHelper.saveToLocalDatabase("F Bomb","Red Blend","Dry","Juicy aromas of strawberry jam, raspberry, and red plum jump out of the glass, with a light framing of toasty vanilla oak.", "Light", "Red", "Santa Barbara County, California", "Not Very", "Greater than $20", "https://images.vivino.com/thumbs/3AR_6eNgSRyJhtu2tvrbAA_pb_x960.png");
        dbHelper.saveToLocalDatabase("Lindeman's Bin 45 Cabernet","Cabernet Sauvignon","Dry","You can't go wrong with an affordable wine sporting deep color, good tannin structure, moderate acidity and aromas of blackcurrant, tomato leaf, dark spices and cedarwood.", "Light", "Red", "Australia", "Not Very", "Less than $20", "https://images.vivino.com/thumbs/YIaCtGWfSpOOQ-ZP9AmlOg_pb_x600.png");

        dbHelper.saveToLocalDatabase("Spier","Chenin Blanc","Sweet","South Africa- Elegant, refreshing and well balanced, displaying aromas that are fresh and fragrant. Filled with tropical fruit, peach and mineral flavors graced with a touch of vanilla on the dry finish.","Light","White","South Africa","Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/ha1/h05/10272950124574.png");
        dbHelper.saveToLocalDatabase("Georgian Legend","Rkatsiteli","Sweet","The typical Rkatsiteli wine is best described as restrained and refreshing, with crisp green-apple flavors and hints of quince and white peach.","Light","White","Georgia","Very","Greater than $20","https://www.bermansfinewines.com/images/sites/bermansfinewines/labels/georgian-legend-rkatsiteli_1.jpg");
        dbHelper.saveToLocalDatabase("Sierra Vista","Barbera","Dry","Wonderful aromas of cherry, strawberry and blackberry complimented by notes of dried lavender and baking spices from the oak.","Heavy","Red","Italy","Very","Greater than $20","https://www.sierravistawinery.com/wp-content/uploads/2019/11/FINAL-Barbera-1.2.jpg");
        dbHelper.saveToLocalDatabase("Ring David","Concord","Between","The Concord wine is juicy and sweet, with an intense grape jam flavor and light finish.","Heavy","Red","Massachusetts","Somewhat","Less than $20","https://www.kosherwine.com/media/catalog/product/cache/a4b4b513774f9733fa68038d5e7329c4/c/a/carmel-king-david-concord-15522-base-5310a9985e214b8c6cca59f289e5b3499ead252d.jpg");
        dbHelper.saveToLocalDatabase("Grand Tokai","Muscat","Between","Muscat Blanc shows a range of citrus, floral and spice aromas, with a full, dry palate. Sparkling and slightly sparkling examples are typically sweeter and tend towards melon flavors, with sweet, grapey smells.","Light","White","Greece","Very","Less than $20","https://www.eurowinesandspirits.com.au/926-thickbox_default/muscat-blanc-2015-grand-tokaj.jpg");

        dbHelper.saveToLocalDatabase("Yalumba 'Y' Viognier","Viognier","Dry","A refreshing Viognier with aromas of honeysuckle, candied ginger and pineapple. Flavors to be found on the palate include fresh pineapple and lychee.","Heavy","White","Australia","Not Very","Greater than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/hd0/h5c/12205797539870.png");
        dbHelper.saveToLocalDatabase("Vista Reserve Cabernet Sauvignon","Cabernet Sauvignon","Dry","One of the more complex and layered wines out there. It has higher tannins and a savory character often described as black pepper and tobacco.","Medium","Red","United States","Not Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/10/2017_Vista_Reserve_Cabernet_Sauvignon_Diamond_Mountain_Napa_Valley_bottle_compressed.png");
        dbHelper.saveToLocalDatabase("Shaw + Smith Chardonnay M3","Chardonnay","Dry","Chardonnay can taste different, depending on where it grows and how it's made. Its flavors range from apple and lemon to papaya and pineapple, and it also shows notes of vanilla when it's aged with oak.","Light","White","Australia","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/03/shawsmith_m3_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Chardonnay Walker","Chardonnay","Dry","Brilliant medium-golden in hue. Aromatically rich, with concentrated notes of grilled pineapple, mango, quince paste, clotted cream, toast, and sweet spice.","Medium","White","United States","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/08/2017_Dutton-Goldfield_Chardonnay_Walker_-_Hill_Vineyard_Green_Valley_of_Russian_River_Valley_2_bottle_compressed.jpg");
        dbHelper.saveToLocalDatabase("Clos Du Val Chardonnay Lot One","Chardonnay","Dry","Medium golden with a lustrous sheen. Tropical passion fruit and pineapple aromas rush from the glass, quickly followed by notions of quince paste, vanilla, clotted cream, allspice, and lilac.","Heavy","White","United States","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/01/2019_Clos_Du_Val_Chardonnay_Lot_One_Carneros_Napa_Valley_bottle_compressed.png");
        dbHelper.saveToLocalDatabase("Kahler Cellars Pinot Noir","Pinot Noir","Dry","Very pale ruby in color. The nose is awash in ripe raspberry, strawberry, and red cherry aromas with hints of cedar, forest floor, and fennel.","Light","Red","United States","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/2018_Kahler_Cellars_Sonoma_County_Pinot_Noir_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Ken Wright Cellars Pinot Noir","Pinot Noir","Dry","Dark ruby center with violet-ruby hues towards the rim. The nose immediately offers warm blueberries, black cherry, and plum, with notes of anise, cola, and spices on the periphery.","Medium","Red","United States","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/kenwright_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Joh. Jos. Prum Riesling Graacher Himmelreich Kabinett","Riesling","Dry","Pale lemon in color, with a slight spritz and a touch of a gold hue. Beautiful citrus and floral aromas await on the nose—peach blossom, linden, lily, fresh lemon, and Kaffir lime.","Light","White","Germany","Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/10/jjprum-graacherhimmelreich_Bottleshot_compressed.jpg");
        dbHelper.saveToLocalDatabase("Domaine Huet Le Haut-Lieu Vouvray","Chenin Blanc","Dry","Medium golden in color, the wine begins with aromas of baked apples, quince, ginger, cedar, and tilled earth. With time, it opens to reveal nuances of clover honey, honeydew melon, saffron, and dried yellow flowers.","Medium","White","France","Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/01/heut-haut-lieu_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("M. Chapoutier Cotes du Rhone","Rhône","Dry","Shows intense aromas of blackcurrant and raspberry complemented by notes of white pepper. In the mouth, this wine is juicy, powerful, and fruity with red fruits and lovely roasted notes.","Heavy","White","France","Very","Greater than $20","https://images.vivino.com/thumbs/jchk9IVTRXmwI0DX8IwAig_pb_600x600.png");
        dbHelper.saveToLocalDatabase("Regis Bouvier En Montre Cul","Pinot Noir","Dry","Pale ruby in color. The wine presents a classic nose of fresh cherry and strawberry, violets, forest floor, licorice, and cedar.","Light","Red","France","Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/04/bouvier-montrecul_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Castello di Verduno Barbaresco","Nebbiolo","Dry","Pouring a clear and bright pale garnet in color. Opens to reveal delicate notions of wild strawberry and raspberry, rose petal, leather, cedar, coriander, anise, and exotic spice.","Medium","Red","Italy","Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/09/verduno-barbaresco-nv_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Esprit de Fonrozay Bordeaux","Merlot","Dry","A soft ruby decorates the glass. Aromas of purple flowers are joined by wild strawberry, cinnamon, and cardamom.","Heavy","Red","France","Very","Less than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/12/2016_Esprit_de_Fonrozay_Bordeaux_bttl__compressed.png");


        dbHelper.saveToLocalDatabase("Chateau Ste Michelle Harvest","Riesling","Between","This sweet Riesling offers rich flavors of ripe peaches balanced with crisp Washington Riesling acidity. It's like a bowl of fruit in a glass!","Light","White","Washington","Not Very","Less than $20","https://images.vivino.com/thumbs/VvbShQz_S4Gjlc6kYNlk-g_pb_x600.png");
        dbHelper.saveToLocalDatabase("Bacalhôa Moscatel de Setúbal","Moscatel","Dry","A rich fortified wine abound with orange tree flower,raisins and a smooth, sweet yet fresh finish. This wine pairs nicely with desserts made with dark chocolate or simply as a digestive with a good coffee.","Light","Red","Portugal","Not Very","Less than $20","https://images.vivino.com/thumbs/HcwOStCNRiK-yeDzXkC_Yw_pb_x600.png");
        dbHelper.saveToLocalDatabase("Cascinetta Vietti Moscato D'Asti","Moscato","Dry","This Moscato d’Asti has intense aromas of peaches, rose petals and ginger. It is delicately sweet and sparkling with balanced acidity, good complexity and a finish of fresh apricots.","Light","White","Italy","Not Very","Less than $20","https://images.vivino.com/thumbs/oFLBf2lSTiqefNRdHShgog_pb_x600.png");
        dbHelper.saveToLocalDatabase("Burmester Tawny Porto","Tawny Port","Between","This Tawny Port has candied fruit aromas, toasted caramel with notes of nuts, giving the wine a subtle elegance. It is full body, smooth, and on the sweet side.","Light","Red","Portugal","Not Very","Less than $20","https://images.vivino.com/thumbs/lamG2abMTqW37CzS3uTA_g_pb_x600.png");
        dbHelper.saveToLocalDatabase("Graham's 20 Year Old Tawny Port","Tawny Port","Between","An excellent bouquet, with a characteristic nutty character and delicious mature fruit with hints of orange peel that is both sweet and smooth on the palate.","Light","Red","Portugal","Not Very","Greater than $20","https://images.vivino.com/thumbs/XSHqBiqMSN-OViOA4o8rJg_pb_x600.png");
        dbHelper.saveToLocalDatabase("Castelfeder Mont Mès","Pinot Grigio","Between","Lively, bright, and golden-tinged. Faint yellow flowers and handfuls of citrus jump out of the glass.","Medium","White","Italy","Not Very","Less than $20","https://images.vivino.com/thumbs/Rep_qZv6RV-Pgsk2QvcFZw_pb_x600.png");
        dbHelper.saveToLocalDatabase("Corte Sant'Alda Soave","Chardonnay","Between","Rich and seductive with an uplifting mineral tone driven by crushed rocks and a citrus layer that makes the mouth water.","Heavy","White","Italy","Not Very","Less than $20","https://images.vivino.com/thumbs/8Gr602BgSPmxJFrP656_JQ_pb_x600.png");
        dbHelper.saveToLocalDatabase("Fattoria di Basciano Chianti Rufina","Sangiovese","Between","Bold, muscular, and attractive, gifted with an opaque ruby core. Aromas led by black cherry and dark plum wrapped in sweet tobacco and herbal spice.","Medium","Red","Italy","Very","Less than $20","https://images.vivino.com/thumbs/giAKCi1pS7-GgrnicihFgg_pb_x600.png");
        dbHelper.saveToLocalDatabase("Finca Mangato Las Estelas Malbec","Malbec","Between","Aromas of blackberry fruit with dark plum fruit on the mid-palate with hints of cracked pepper, licorice, cloves, and kola nut.","Medium","Red","Italy","Not Very","Less than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/03/2017_Finca_Mangato_Las_Estelas_Malbec_Alto_bottle_compressed.jpg");
        dbHelper.saveToLocalDatabase("Old Vines Field Blend","Carignan","Between","Dark purple-ruby center with violet highlights at the rim. The palate shows woodsy dried herbs with pine needles, sandalwood, and cracked pepper.","Heavy","Red","California","Not Very","Less than $20","https://images.vivino.com/thumbs/F4EH1rtSTtS0HXBZXBDGdg_pb_x600.png");
        dbHelper.saveToLocalDatabase("Weingut Bossert Pinot Blanc","Pinot Blanc","Between","Crisp and mineral-laden, the palate displays fresh lemon zest and a green apple crispness, with a touch of spice on a vibrant finish.","Light","White","Germany","Somewhat","Less than $20","https://wineguide.wein.plus/uploads/media/wine_wine/196877/conversions/public.png");
        dbHelper.saveToLocalDatabase("Best's Great Western Riesling","Riesling","Between","The mouthfeel is complex, with crisp notes characterized by citrus. A touch of sweetness resolves in a mineral layer that lasts forever.","Medium","White","Australia","Somewhat","Less than $20","https://images.vivino.com/thumbs/Pmj_OHtaQomC9UjM6uSVMA_pb_x600.png");
        dbHelper.saveToLocalDatabase("Leone d'Almerita","Chardonnay","Between","Bright lemon-green in color, Leone offers aromas of pink grapefruit, orange blossom, white peach, and pineapple.","Heavy","White","Italy","Somewhat","Less than $20","https://images.vivino.com/thumbs/o2fsnnS7R5KVmNjkRwEgdA_pb_x600.png");
        dbHelper.saveToLocalDatabase("La Grange de Piaugier","Shiraz","Between","Deep ruby-purple and viscous. Meaty aromas of wild strawberry, black raspberries, cracked pepper, smoked meats, and dried herbs will grab you immediately.","Light","Red","France","Somewhat","Less than $20","https://images.vivino.com/thumbs/yjw_8jwxSHq8Sum4cYbRmQ_pb_x600.png");
        dbHelper.saveToLocalDatabase("Alcance Vigno Carignan Old Vines","Carignan","Between","The aromatics show an integration of blackberry, dried violet, wild herb, and a kiss of smoke. There are tones of licorice, wild game, and black peppercorn on the palate.","Medium","Red","Chile","Somewhat","Less than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/01/2014_Alcance_Vigno_Old_Vines_Dry_Farmed_Carignan_Maule_Valley_Chile_bttl_compressed.png");
        dbHelper.saveToLocalDatabase("Langhe Arneis Montebertotto","Arneis","Between","Broad on the palate, yet fresh thanks to its lively acidity. Citrusy lemon flavors join in on the palate along with the pear and apple notes, underpinned by a nutty, earthy contrast for a complex, layered mouthfeel.","Medium","White","Italy","Very","Less than $20","https://images.vivino.com/thumbs/J5QS5_0sRLWJDqq73quZnQ_pb_x600.png");
        dbHelper.saveToLocalDatabase("Giuseppe e Luigi Pinot Grigio","Pinot Grigio","Between","Bright, golden-tinged concentration in the glass. Aromas of yellow flowers and honeysuckle stand out, followed by layers of Sicilian lemon zest and crushed limestone.","Heavy","White","Italy","Very","Less than $20","https://images.vivino.com/thumbs/GIAZB307SyypjGwmW8RYdw_pb_x600.png");
        dbHelper.saveToLocalDatabase("Winter's Hill Pinot Noir","Pinot Noir","Between","Bright ruby center with ruby reflections throughout. The nose is centered around red fruits such as candied raspberry, red cherry, and crushed red plum.","Light","Red","Oregon","Very","Less than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/04/wintershill_pn_dh_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Martin Ray Cabernet Sauvignon","Cabernet Sauvignon","Between","Dark ruby-black at the center with crimson-violet staining tears. The nose opens to black currant, blackberry, crushed bay leaf, and shaved chocolate.","Heavy","Red","California","Very","Less than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/04/mr-napa-cab-19_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Trifolé Dolcetto d'Alba","Dolcetto","Sweet","A powerful wine with impact and finesse. The mouthfeel is complex and memorable with sour cherry, hibiscus, and a savory kiss that carries intensity and a rich tannic structure.","Light","Red","Italy","Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/03/2018_Bruno_Rocca_Trifole_Dolcetto_DAlba_DOC_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Le Haut-Médoc de Pédesclaux","Cabernet Sauvignon","Sweet","Medium-bodied, it shows pleasantly crunchy tannins and a beautifully lifted frame that showcase flavors of black raspberry, wild herbs, spice box, and cedar.","Medium","Red","France","Very","Greater than $20","https://images.vivino.com/thumbs/4Qc2T4bJRwmauc6URgYtZQ_pb_x600.png");
        dbHelper.saveToLocalDatabase("Blackbird Vineyards Arise Red","Cabernet Sauvignon","Sweet","Adorned with raspberry, black plum, freshly roasted espresso, and spice, it boasts broad shoulders and finesse. It’s  an instantly satisfying Bordeaux blend.","Heavy","Red","California","Very","Greater than $20","https://images.vivino.com/thumbs/K2qCNGTRRQGr68n7yV7pcQ_pb_x600.png");

        dbHelper.saveToLocalDatabase("Domaine Grand Veneur","Les Champions","Between","The red wines can be fruity, sweet, spicy and packed with ripe, red berries. The wines can be sweet, fruity and easy to drink.","Heavy","Red","France","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hf5/hcd/8815668854814.png");
        dbHelper.saveToLocalDatabase("Chateau D'Esclans","Blush Rose","Dry","This is full of mouthwatering flavor with a lovely texture. Lots of light fruit flavors with a clean finish, this wine does well to demonstrate the power of its grape.","Medium","White","France","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/ha9/hbf/12357383290910.png");
        dbHelper.saveToLocalDatabase("Valserrano Rioja Reserva","Tempranillo","Dry","An elegant , savoury cuvee of Tempranillo and 10% Graciano with savoury tannins and fine, graceful, red berry and fresh herb notes.","Heavy","Red","Spain","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hec/h42/10069521858590.png");
        dbHelper.saveToLocalDatabase("Alta Nova Cabernet Napa","Cabernet Sauvigno","Dry","Aromas of concentrated red and black cherry, cassis, cranberry and pomegranate. Savory notes of olive tapenade, tar, licorice, graphite, and pepper.","Heavy","Red","Napa Valley California","Somewhat","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/ha9/hd5/13986845949982.png");
        dbHelper.saveToLocalDatabase("Trimbach Riesling","Cuvee Emile","Sweet","One of the firms flagship bottlings, this superb dry Riesling hails from 2 Grand Cru vineyards, Geisberg and Osterberg. Clearly one of Alsace's greatest wines.","Heavy","White","Alsace-France","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h9d/h87/8806085197854.png");
        dbHelper.saveToLocalDatabase("Fleur De Mer Rose","Rose","Between","A classic Provençal Rosé, Fleur de Mer is a brilliant pale pink color, beautifully balanced with bright fruit notes and crisp acidity.","Light","White","France","Not Very","Greater than $20","https://www.thebarrelroom.com/dw/image/v2/BFWT_PRD/on/demandware.static/-/Sites-gallo-master-catalog/default/dw29cce83f/images/0503801OS/0503801OS.png");
        dbHelper.saveToLocalDatabase("Avaline White","Blend","Between","This is a vibrant Spanish white bursting with fruit. Dry in style, flavors of citrus and pear on the palate with a crisp, freshness on the finish.","Medium","White","Spain","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/haf/h29/13565730062366.png");
        dbHelper.saveToLocalDatabase("Don Q Seleccion Especial","Berlsel","Between","A blend of medium and heavy bodied rums, with a touch of Solera aged rums resulting in a unique blend with intense and complex aromas.","Heavy","White","Puerto Rico","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h5c/h48/14196461469726.png");
        dbHelper.saveToLocalDatabase("Plymouth Sloe","Gin","Between","Red and black berry aromas abound. Slightly viscous in the mouth with hints of coriander underneath the concentrated berry flavors.","Medium","Red","England","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hfd/he4/12217775423518.png"); //56
        dbHelper.saveToLocalDatabase("Amici Sauvignon Blanc Napa","Sauvignon Blac","Between","A sauvignon blanc with very pretty sliced lemons and light fennel seeds with some crushed cement. It's full-bodied with a round, creamy texture. Delicious now.","Light","White","Napa Valley","Somewhat","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h10/h7b/11931321499678.png");//58
        dbHelper.saveToLocalDatabase("Dr Heidemanns Bernkastel","Riesling","Between","Bracing whiffs of orange zest and blossom brighten this gorgeously honeyed Riesling.","Medium","White","Germany","Somewhat","Greater than $20","https://www.totalwine.com/dynamic/x490,375ml/media/sys_master/twmmedia/heb/h01/8812511789086.png");//59
        dbHelper.saveToLocalDatabase("Domaine Pascal Bouchard","Chablis","Between","Displaying a beautiful fragrance, filled with slate and apple, leading to a vibrant, yet rich, mouthful of mineral and citrus flavors.","Heavy","White","Burgundy","Somewhat","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h8e/ha9/8815715713054.png");//60
        dbHelper.saveToLocalDatabase("Chateau Haura Graves","Bordeaux Blend","Between","Solid cherry and plum paste notes are backed by a light tar streak. Offers a focused, fresh finish","Light","Red","France","Somewhat","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hd4/hd8/11900799582238.png");//61
        dbHelper.saveToLocalDatabase("Penfolds Cabernet","Shiraz Bin","Between","Elegant, smooth and supple, showing off cedar, black tea and sandalwood aromas, with plenty of restraint. The raspberry coulis, blood orange notes at the center are wonderfully pure.","Medium","Red","Autralia","Somewhat","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h64/he0/11931351777310.png");//62
        dbHelper.saveToLocalDatabase("Caymus Cabernet","Sauvignon","Between","Featuring decadent ripe blackberry flavors with undertones of vanilla and toasted oak. A rich and delicious wine, ready to enjoy now!","Heavy","Red","Napa Valley","Somewhat","Greater than $20","https://www.totalwine.com/dynamic/x490,375ml/media/sys_master/twmmedia/hba/hce/12357542510622.png");//63
        dbHelper.saveToLocalDatabase("Frog's Leap Sauvignon","Blanc","Between","This wine sees no oak and made in a fresh friendly style. It has a lovely grapefruit nose, hinting at citrus and fig nuances.","Light","White","Napa Valley","Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/he5/h71/12291777232926.png");//64
        dbHelper.saveToLocalDatabase("Javillier Bourgogne Des Forgets","Chardonnay","Between","One of Burgundy's best regional wines, this selection is loaded with ripe pear flavors and buttered toast overtones.","Medium","White","Burgundy","Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h32/hfb/8802898149406.png");//65
        dbHelper.saveToLocalDatabase("Ch Cote Montpezat Cuvee","Compostelle Blanc","Between","Fresh white wine with flavors of citrus, and quiet creamy with almond notes. Pairing this wine with white fish like Cod and season vegetables.","Heavy","White","Bordeaux","Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h76/h5c/8799618564126.png");//66
        dbHelper.saveToLocalDatabase("Mauro Sebaste D'Alba","Barbera","Between","Grown in the foothills of the Italian Alps, this bright, supple red is low in tannins and filled with ripe red fruits and dark flower notes.","Light","Red","Italy","Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hce/h70/12007040811038.png");//67
        dbHelper.saveToLocalDatabase("Muga Rioja Seleccion Reserva","Muga","Between","The balance and purity to this wine is really impressive with blackberries, black truffles and dark fruit.","Medium","Red","Rioja","Very","Greater than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hf3/he7/10719432736798.png");//68

        dbHelper.saveToLocalDatabase("Castelfeder Mont Mes", "Pinot Grigio", "Dry", "This is a dry white wine with relatively high acidity. These characteristics are complemented by aromas of lemon, lime, green apple and blossoms.", "Light", "White", "Italy", "Not Very", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2020/07/2019_Castelfeder_Mont_Mes_Pinot_Grigio_Vignetti_delle_Dolomiti_IGT_bottle_compressed.jpg");
        dbHelper.saveToLocalDatabase("Domaine du Clos du Fief", "Gamay", "Dry", "A fruity, floral and sometimes earthy light-bodied red that is the main variety planted in Beaujolais. Outside of France, Gamay has a tiny but devoted following.", "Light", "Red", "France", "Not Very", "Greater than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2020/12/2019_Domaine_du_Clos_du_Fief_Tradition_Cru_Julienas_Beaujolais_France_compressed.png");
        dbHelper.saveToLocalDatabase("Martin Codax Albarino", "Albarino", "Dry", "Albariño wine is a delightfully refreshing coastal white that grows on the Iberian Peninsula. It’s loved for its rich stone fruit flavors, a hint of salinity, and zippy acidity", "Light", "White", "Spain", "Not Very", "Less than $20", "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h78/h23/12343349870622.png");
        dbHelper.saveToLocalDatabase("Chateau Saint-Roch", "Grenache", "Dry", "Saturated dark ruby hue. Heaps of black fruit and earth on the nose. Voluptuous and layered on the palate with dark plum and blueberry fruit.", "Light", "Red", "France", "Not Very", "Greater than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2020/03/saint-roch_Bottleshot_compressed.jpg");
        dbHelper.saveToLocalDatabase("Quinta do Noval Vintage", "Port", "Dry", "This wine boasts plenty of black cherry preserves, crushed blackberry, crushed violets, cracked peppercorn, cardamom, cedar, rose petal, and star anise character. Taut and lean, but still full-bodied.", "Light", "Red", "Portugal", "Not Very", "Greater than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/01/2018_Quinta_do_Noval_Vintage_Port_Douro_Valley_Portugal_bottle_compressed.png");
        dbHelper.saveToLocalDatabase("M. Chapoutier Banyuls", "Banyuls", "Dry", "Deep ruby-garnet. Dried fruits, crystallized orange peel and freshly cracked black pepper on the nose. Rich layers of dried plum, dark chocolate and a hint of baking spices on the palate.", "Light", "Red", "France", "Not Very", "Greater than $20", "https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/fs1gurtuqrwsvcp4zwzs.jpg");
        dbHelper.saveToLocalDatabase("Inniskillin Vidal Icewine", "Ice Wine", "Dry", "Aromatics of tropical fruit including mango and orange dominate, on the palate fruit flavors including peach, nectarine and lemon are balanced by crisp, lively acidity.", "Light", "White", "Canada", "Not Very", "Greater than $20", "https://images.vivino.com/thumbs/BCR0dcHqTgCyi9s_kBxOUw_pb_x600.png");
        dbHelper.saveToLocalDatabase("Weingut Stadt Krems", "Grüner Veltliner", "Dry", "Aromatic notes of crisp green apple, lime zest, freshly picked watercress, and radish race down the middle of the palate.", "Light", "White", "Austria", "Not Very", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/2019_Weingut_Stadt_Krems_Gruner_Veltliner_Kremstal_Austria_Bottleshot_compressed.png");

        dbHelper.saveToLocalDatabase("Saint-Nicolas-de-Bourgueil", "Cabernet Franc", "Between", "This is a Complex red with aromas of raspberry, bramble, and bell pepper. You could pair this with tomato-based dishes, vinegar-based sauces.", "Heavy", "Red", "France", "Very", "Greater than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/03/2018_Pascal_et_Alain_Lorieux_Cuvee_Agnes_Sorel_Saint-Nicolas-de-Bourgueil_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Sutter Home Gewurztraminer","Gewurztraminer", "Sweet", "This medium-sweet Gewurztraminer boasts notes of lush lychee fruit, fresh white berries and rose petals, balanced beautifully by a hint of allspice, cinnamon, and baking spices.", "Light", "White", "California", "Not Very", "Less than $20", "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h98/h90/12343415341086.png");
        dbHelper.saveToLocalDatabase("Best's Great Western Riesling","Riesling", "Sweet", "A lively platinum green decorates the glass. Aromas are led by a bounty of white florals with yellow lemon zest, plus a generous dose of nectarine and wet stones. The mouthfeel is complex, with crisp notes characterized by citrus. A touch of sweetness resolves in a mineral layer that lasts forever.", "Medium", "White", "Australia", "Not Very", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/04/bests-greatwestern-riesling_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Reverchon Riesling Kabinett Ockfener Bockstein", "Riesling", "Sweet", "A brass-tinged core with platinum around the rim. An aromatic masterpiece with layers of Meyer lemon preserves, white pepper, and jasmine blossoms. The mouthfeel is driven by rich citrus and unveils a mouthwatering salty layer with vibrancy and minerals before resolving in a long finish.", "Heavy", "White", "Germany", "Not Very", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/04/reverchon_onrk_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Graham’s Late Bottled Vintage", "Port", "Sweet", "This delicous LBV shows a stunning intensity on the nose, packed with red and jammy black fruit aromas. On the palate full bodied and robust, with an exceptional velvety and well-rounded structure, leading to a complex and fruit-driven finish.", "Heavy", "Red", "Portugal", "Somewhat", "Less than $20", "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hcd/h89/8806088343582.png");
        dbHelper.saveToLocalDatabase("Patricius 'Katinka' Noble Late Harvest", "Tokaji", "Sweet", "A notable Hungarian sweet wine made mostly of Furmint grapes that are affected by a special rot called Botrytis cinerea. The rot concentrates the grape’s sugars and adds distinct aromas of ginger and saffron.", "Medium", "White", "Hungary", "Very", "Less than $20", "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwine-searcher1.freetls.fastly.net%2Fimages%2Flabels%2F10%2F60%2Fpatricius-katinka-noble-late-harvest-tokaji-tokaj-hegyalja-hungary-10481060.jpg&f=1&nofb=1");
        dbHelper.saveToLocalDatabase("Dr. H. Thanisch Riesling", "Riesling", "Sweet", "Bright platinum with an inviting green hue. A mineral-rich layer awakes the senses with clay and blue slate uncovering a blanket of green nectarine and lemon blossom. The mouthfeel is exciting and lively with mouthwatering acidity and a long finish.", "Light", "White", "Germany", "Somewhat", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/2018_Dr._H._Thanisch_Feinherb_Riesling_Mosel_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Cuvee La Galline Banyuls", "Banyuls", "Sweet", "One of France’s most important sweet, fortified Vin Doux Naturel wines made primarily of Grenache and/or Grenache Blanc grapes.", "Heavy", "Red", "France", "Not Very", "Less than $20", "https://www.albertuswijnen.nl/images/watermarked/1/detailed/1/Banyuls_-_Vin_Doux_Naturel_-Cuve%C3%A9_La_Galline-.jpg");
        dbHelper.saveToLocalDatabase("Quinta Das Carvalhas Ruby Reserva", "Port", "Sweet", "This deep ruby port has dark berry fruits deepened creating a sweet jammy flavor. Well structured, this port will linger in your mouth with a tinge of spice. Pair with medium strong cheeses.", "Medium", "Red", "Portugal", "Somewhat", "Less than $20", "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hd1/hca/8806011240478.png");
        dbHelper.saveToLocalDatabase("Porto Valdouro ", "White Port", "Sweet", "Clear colour with a golden hue. This white port has complex floral aromas and a medium bodied palate, full of ripe fruit and a touch of honey before a long finish. This is an excellent base for a cocktail or chill and serve alone.", "Heavy", "White", "Portugal", "Very", "Less than $20", "https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h47/hf3/9942989864990.png");
        dbHelper.saveToLocalDatabase("Chateau Dudon Gallien", "Sauternes", "Sweet", "Rich golden core with a copper rim. A cornucopia of layers led by acacia and jasmine, ginger, and lemon laced with wild honey. The mouthfeel is elegant and comforting, with plenty of Meyer lemon peel, yellow nectarine, and zippy acidity that balances the kiss of sweet.", "Heavy", "White", "France", "Somewhat", "Less than $20", "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.wine-calais.co.uk%2F14049-thickbox_default%2Fgallien-sauternes-by-chateau-dudon-2019.jpg&f=1&nofb=1");
        dbHelper.saveToLocalDatabase("Alto Adige Lagrein", "Schiava", "Sweet", "A fascinating fruity red wine that grows in the northern parts of Italy, particularly in Trentino-Alto Adige, that offers up bold fruity aromas of rose, cotton candy, sweet cherry sauce and cinnamon.", "Light", "Red", "Italy", "Somewhat", "Less than $20", "https://s.tannico.it/media/catalog/product/cache/43/thumbnail/0dc2d03fe217f8c83829496872af24a0/l/a/lagrei1_1_1_1_1_2.jpg");
        dbHelper.saveToLocalDatabase("Pietradolce Etna Rosso Sicily", "Etna Rosso", "Sweet", "Vibrant ruby in color with darker ruby undertones. The nose offers fresh Bing cherry, candied raspberry, and cranberry. There is a juiciness to the fruit that feels buoyant and crisp. Wildflowers, wet stones, and sweet citrus peels fill the edges of the glass, while a more serious and defined structure keeps the wine nicely composed.", "Light", "Red", "Italy", "Not Very", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/01/2019_Pietradolce_Etna_Rosso_Sicily_bottle_compressed.png");
        dbHelper.saveToLocalDatabase("Paul Jaboulet Aîné Secret", "Côtes-du-Rhône", "Sweet", "Showing a medium ruby color with a dense core. Bold aromas of black raspberry, wild strawberry, garrigue, cracked peppercorn, fennel, and smoked meat rise from the glass. On entry the wine is fruit-forward, but the flavors of red and black fruits evolve towards savory smoke, dried herbs, and spice.", "Medium", "Red", "France", "Not Very", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2020/10/pja-secret_nv_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Corte Sant'Alda Soave", "Garganega", "Sweet", "A perfect example of a terroir-driven wine. Exhibiting a lively copper core with hints of gold on the rim. An array of yellow and white flowers decorates the senses, rounded by aromas of freshly cut summer nectarine, Meyer lemon peel, tarragon, and chamomile. ", "Medium", "White", "Italy", "Somewhat", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2020/09/2019_Corte_SantAlda_Soave_Veneto_bttl_compressed.png");
        dbHelper.saveToLocalDatabase("Fattoria di Basciano", "Chianti Rufina", "Sweet", "Bold, muscular, and attractive, gifted with an opaque ruby core. Aromas led by black cherry and dark plum wrapped in sweet tobacco and herbal spice. The mouthfeel is generous and instantly satisfying with grand fruit balanced by mineral undertones and resolving in big tannins and a long finish.", "Light", "Red", "Italy", "Very", "Less than $20", "https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/Basciano_rufina_Bottleshot_compressed.png");

        dbHelper.saveToLocalDatabase("DISTRICT SERIES CABERNET ALEXANDER VALLEY, 2019","Cabernet Sauvignon","Between","The Tasting Panel-Alexander Valley, CA- Imagine an Alexander Valley Cab at this price that displays noticeably plush tannins with dark chocolate dust. Blueberry notes are generous and rich, and a dollop of Cabernet Franc adds a note of dried heather.","Heavy","Red","California","Somewhat","Less than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hef/hd1/13771982667806.png");
        dbHelper.saveToLocalDatabase("MASCOTA VINEYARDS LA MASCOTA CABERNET SAUVIGNON, 2018","Cabernet Sauvignon","Dry","James Suckling-Mendoza, Argentina - Brambleberries, dried plums and spices with a hint of dried fruit. Fruity on the palate with juicy tannins and a medium-chewy finish. This fruitfilled Cabernet pairs well with steak.","Medium","Red","Mendoza","Not Very","Less than $20","https://www.totalwine.com/dynamic/x220,sq/media/sys_master/twmmedia/h1b/h78/12279044636702.png");
        dbHelper.saveToLocalDatabase("ANGELINE PINOT NOIR RESERVE, 2018","Pinot Noir","Dry","James Suckling-Mendocino County, California - Cool aromas of dried strawberries and fresh herbs. Medium body, very creamy tannins and a long, flavorful finish. Soft and fresh. Try pairing with salmon, chicken, or pasta dishes.","Medium","Red","Mendocino","Not Very","Less than $20","https://www.totalwine.com/dynamic/x220,sq/media/sys_master/twmmedia/hb9/hc4/12291914235934.png");
        dbHelper.saveToLocalDatabase("HALL RANCH ZINFANDEL PASO ROBLES, 2018","Zinfandel","Between","Beverage Dynamics-Paso Robles, California - If you haven't found a Zin you like, try this one! Dense, soft tannins with dark cherry and a hint of black bramble and cinnamon. Serve with something off the grill or a nice soft goat cheese.","Heavy","Red","Central Coast","Not Very","Greater than $20","https://www.totalwine.com/dynamic/x220,sq/media/sys_master/twmmedia/h85/h4f/13376584515614.png");
        dbHelper.saveToLocalDatabase("FIREBRAND CHARDONNAY RESERVE, 2019","Chardonnay","Dry"," Beverage Dynamics-California - Green apple aromas jump out of the glass and follow onto the palate with oak vanilla flavors for structure. The wine is fun, energetic and approachable. Pairs well with seafood, pasta, and mild cheese.","Heavy","White","California","Somewhat","Less than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h47/h51/13287128465438.png");
        dbHelper.saveToLocalDatabase("Fattoria di Basciano Chianti","Chianti","Sweet","This beautifully crafted Chianti brought our conversation to a dead stop" ,"Medium","Red","Italy","Very","Less than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/Basciano_rufina_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Marqués del Atrio Rioja Reserva","Carignan","Sweet","This one of Spain’s best values of the year, a 93-point Reserva at a price that you almost never see.","Heavy","Red","Spain","Very","Less than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/03/atrio_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Tokaj Oremus Tokaji Aszú","Tokaji","Sweet","Tokaji is a cellar essential, especially when it comes from Vega Sicilia-backed Oremus.","Light","White","Hungary","Not Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/09/2010_Tokaj_Oremus_Tokaji_Aszu_5_Puttonyos_Tokaj_Hungary_bottle_compressed.jpg");
        dbHelper.saveToLocalDatabase("Dr. Pauly-Bergweiler Riesling Kabinett","Riesling","Sweet","Luscious perfection made from the top vineyard in the peak region for Riesling","Medium","White","Germany","Not Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/03/2018_Dr._Pauly-Bergweiler_Wehlener_Sonnenuhr_Kabinett_Riesling_Mosel__bottle_compressed.png");
        dbHelper.saveToLocalDatabase("Paxton MV Shiraz McLaren Vale","Shiraz","Sweet","Wines from Paxton grapes are hot-ticket collector items—the coveted Mollydooker Velvet Glove Shiraz costs $195.","Light","Red","Australia","Not Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/01/2019_Paxton_MV_Shiraz_McLaren_Vale_Australia_bottle_compressed.png");
        dbHelper.saveToLocalDatabase("Le Grand Bouqueteau Chinon","Cabernet Franc","Sweet","This Cab Franc is a delicious lesson in all that makes the Loire Valley so special.","Medium","Red","France","Not Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2019/12/Chinon_compressed.jpg");
        dbHelper.saveToLocalDatabase("Vista Reserve Cabernet Sauvignon","Cabernet Sauvignon","Sweet","From an estate whose muscular Cabernet Sauvignons go for over $100 and pull down 95+ point scores. ","Heavy","Red","USA","Not Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/10/2017_Vista_Reserve_Cabernet_Sauvignon_Diamond_Mountain_Napa_Valley_bottle_compressed.png");
        dbHelper.saveToLocalDatabase("Grosset Wines Alea","Riesling","Sweet","Grosset is one of Australia’s iconic producers—the undisputed master of Riesling on the continent.","Light","White","Clare Valley","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/2020_Grosset_Wines_Alea_Riesling_Clare_Valley_Australia_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Gustave Lorentz ","Gewurztraminer","Sweet","Alsatian Gewürztraminer with this much spicy character and steely acidity can rarely be found for under $50","Medium","White","France","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/2019_Gustave_Lorentz_Gewurztraminer_Reserve_Alsace_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Best's Great Western ","Riesling","Sweet","This is one of the most age-worthy white wines made in the southern hemisphere.","Light","White","Australia","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/04/bests-greatwestern-riesling_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Dayna Estate Cabernet Sauvignon Oak","Cabernet Sauvignon","Sweet","From a seasoned Cabernet expert behind icons like Joseph Phelps, Chateau Montelena, and Robert Mondavi.","Light","Red","Napa Valley","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/11/2018_Dayna_Estate_Cabernet_Sauvignon_Oak_Knoll_District_Napa_Valley_bottle_compressed.png");
        dbHelper.saveToLocalDatabase("Mas Roc de Bô Pepite Noir","Syrah","Sweet","This is a dead-ringer for high-end Châteauneuf, with a price that’s pure Languedoc.","Medium","Red","France","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/11/mas-roc-pepite_Bottleshot_compressed.png");
        dbHelper.saveToLocalDatabase("Famille Perrin Les Sinards","Cabernet Sauvignon","Sweet","Today’s 94pt Editors’ Choice Châteauneuf is from the same terroir and far less off a price!","Heavy","Red","France","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/06/lessinards_Bottleshot_compressed.jpg");
        dbHelper.saveToLocalDatabase("Chateau Haut Bergeron Sauternes","Semillion","Sweet","Decanter called it “pitch-perfect” while awarding it a 96-point score.","Medium","White","France","Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2020/09/2016_Chateau_Haut-Bergeron_Sauternes_AOC_bottle_compressed.jpg");
        dbHelper.saveToLocalDatabase("Tasca d'Almerita Tenuta Regaleali","Catarratto","Sweet","In 2019, Tasca d’Almerita became the first Sicilian producer to earn a Wine Enthusiast Winery of the Year award.","Heavy","White","Italy","Very","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/04/dAlmerita-catarratto_Bottleshot_compressed.png");

        dbHelper.saveToLocalDatabase("Rocca Felice Roero Arneis","Arneis","Dry","On the mouth, it is dry, appealing and harmonious.| Medium | White | Piedmont, Italy | Not Very | Less than $20 ","Medium","White","Piedmont, Italy","Not Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h03/h57/11019502714910.png");
        dbHelper.saveToLocalDatabase("Hermes Greek White","White blend","Dry","With a hint of peach in its nose, it is straw in color and has hints of herbal notes.","Heavy","White","Greece","Not Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h5c/h8c/9155808198686.png");
        dbHelper.saveToLocalDatabase("Double Black Zinfandel","Zinfandel","Dry","This full-bodied, elegant wine explodes with dark berry flavors and finishes with cracked pepper spice. Excellent with BBQ ribs, skirt steak, grilled sausages, and pasta marinara." ,"Heavy","Red","Paso Robles, California","Not Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h85/hc1/13287126728734.png");
        dbHelper.saveToLocalDatabase("Cortese organic nostru catarratto lucido terre siciliane IGP","Catarratto","Dry","A light bright white peach and lemon style that has a smooth delivery of fresh fruit flavor and a gently stony thread at the finish.","Light","White","Sicily, Italy","Somewhat","Less than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/hf8/h9b/11698280071198.png");
        dbHelper.saveToLocalDatabase("Mauro Sebaste Gavi ","Cortese","Dry","With tropical fruit, acacia flower and honey character. Medium-bodied, with a rich, flavorful palate and finish. ","Medium","White","Piedmont, Italy","Somewhat","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/hdc/hcd/12007040843806.png");
        dbHelper.saveToLocalDatabase("Bulgariana Gamza","Gamay","Dry","A full-bodied wine with aromas of red fruits, freshness, and a ruby red color.","Light","Red","Bulgaria","Somewhat","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h46/hea/10997580431390.png");
        dbHelper.saveToLocalDatabase("Asua Rioja Crianza","Tempranillo","Dry","It might be a little more floral, but it has the darker fruit... It's serious but easy to drink and has the approachability and freshness. ","Medium","Red","Rioja, Spain","Somewhat","Less than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h06/hb0/12306864734238.png");
        dbHelper.saveToLocalDatabase("Decoy Cabernet Sauvignon ","Cabernet Sauvignon","Dry","From its deep, inviting color to its enticing layers of boysenberry, blackberry, plum and star anise, this wine showcases great Sonoma County Cabernet Sauvignon.","Heavy","Red","Sonoma County, California","Somewhat","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h78/he2/12674919497758.png");
        dbHelper.saveToLocalDatabase("Dr. Heidemanns Riesling Dry ","Riesling","Dry","Heady white-blossom aromas are juxtaposed by cut stones and mineral on the nose of this cutting dry Riesling. The palate offers pert lemon and lime edged by a hint of citrus pith.","Light","White","Mosel, Germany","Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h8d/hd5/8812522504222.png");
        dbHelper.saveToLocalDatabase("Gerd Anselmann Pfalz Riesling Dry ","Riesling","Dry","This dry white Riesling from the Pfalz region of Germany features tender acidity with a pleasant body.","Medium","White","Pfalz, Germany","Very","Less than $20","https://www.totalwine.com/dynamic/x490,sq/media/sys_master/twmmedia/h41/h71/9496603263006.png");
        dbHelper.saveToLocalDatabase("Buttercream Chardonnay ","Chardonnay","Dry","Tastes like silken butter dripped over a fresh croissant.","Heavy","White","California","Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h00/h86/14091576377374.png");
        dbHelper.saveToLocalDatabase("Louis Bouillot Perle D’Aurore Brut Rose","Rose","Dry","A sophisticated Rose made using the Champagne method from Pinot Noir grapes.","Light","Red","Burgundy, France","Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h0e/h06/12262839189534.png");
        dbHelper.saveToLocalDatabase("Giribaldi Barbera D'ALBA","Barbera","Dry","The juicy palate doles out black cherry, raspberry jam, licorice and a touch of orange zest alongside bright acidity and polished tannins.","Medium","Red","Piedmont, Italy","Very","Less than $20","https://www.totalwine.com/dynamic/490x/media/sys_master/twmmedia/h0d/h54/14252073615390.png");

        dbHelper.saveToLocalDatabase("Gustave Lorentz","Alsace","Sweet","With this much spicy character and steely acidity can rarely be found for under $50.","Heavy","White","France","Somewhat","Greater than $20","https://dco67j8qsiydp.cloudfront.net/images/products/2021/02/2019_Gustave_Lorentz_Gewurztraminer_Reserve_Alsace_Bottleshot_compressed.png");


    }

    public void openWineDishes()
    {
        Intent intent = new Intent(this, WineDishes.class);
        startActivity(intent);
    }

    public void openWineCollection()
    {
        Intent intent = new Intent(this, WineDatabaseCollection.class);
        startActivity(intent);
    }

    public void openWineSurvery()
    {
        Intent intent = new Intent(this, Wine_Survey.class);
        startActivity(intent);
    }

    public void openProfileSetUp()
    {
        Toast.makeText(this, "You are signed out!", Toast.LENGTH_SHORT).show();
        Intent intent = new Intent(this, ProfileSetUp.class);
        startActivity(intent);
    }

    public void openOnboardingAHelp()
    {
        Intent intent = new Intent(this, OnboardingActivityHelp.class);
        startActivity(intent);
    }


}